# Generated by Django 5.2.1 on 2025-06-22 09:18

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('timestamp', models.FloatField()),
                ('proof', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('nonce', models.CharField(max_length=255)),
                ('merkle_root', models.CharField(max_length=255)),
                ('difficulty', models.FloatField(blank=True, default=4.0, null=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_supply', models.FloatField(default=0.0)),
                ('max_supply', models.FloatField(default=210000000.0)),
                ('current_reward', models.FloatField(default=0.05)),
                ('halving_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('difficulty', models.FloatField(default=4.0)),
            ],
            options={
                'verbose_name': 'Blockchain State',
                'verbose_name_plural': 'Blockchain States',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Upload')], max_length=50)),
                ('sender_public_key', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='transaction_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'xlsx', 'xls', 'doc', 'docx', 'txt'])])),
                ('timestamp', models.FloatField()),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_symmetric_key', models.BinaryField(blank=True, null=True)),
                ('receiver_public_key_at_encryption', models.TextField(blank=True, null=True)),
                ('max_downloads', models.IntegerField(blank=True, default=None, null=True)),
                ('current_downloads', models.IntegerField(default=0)),
                ('is_viewed', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Cripto1.block')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('private_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cripto1.block')),
                ('deployer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cripto1.userprofile')),
            ],
        ),
    ]
