# Generated by Django 5.2.3 on 2025-06-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cripto1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainstate',
            name='max_supply',
            field=models.FloatField(default=21000000.0),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registrazione'), ('CREATE_TRANSACTION', 'Creazione Transazione'), ('VIEW_TRANSACTION', 'Visualizzazione Transazione'), ('DOWNLOAD_FILE', 'Download File'), ('DECRYPT_MESSAGE', 'Decifratura Messaggio'), ('MINE_BLOCK', 'Mining Blocco'), ('EDIT_PROFILE', 'Modifica Profilo'), ('RESET_PRIVATE_KEY', 'Reset Chiave Privata'), ('ADMIN_ACTION', 'Azione Amministrativa'), ('SECURITY_EVENT', 'Evento di Sicurezza'), ('EXPORT_DATA', 'Export Dati'), ('VERIFY_BLOCKCHAIN', 'Verifica Blockchain'), ('USER_MANAGEMENT', 'Gestione Utenti'), ('SYSTEM_EVENT', 'Evento di Sistema')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Basso'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Critico')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action_type', 'timestamp'], name='Cripto1_aud_user_id_531a62_idx'), models.Index(fields=['action_type', 'timestamp'], name='Cripto1_aud_action__584e8f_idx'), models.Index(fields=['severity', 'timestamp'], name='Cripto1_aud_severit_682fec_idx'), models.Index(fields=['ip_address', 'timestamp'], name='Cripto1_aud_ip_addr_f6f36a_idx')],
            },
        ),
    ]
