# Generated by Django 5.2.3 on 2025-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cripto1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_encrypted_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_encrypted_symmetric_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
