# Generated by Django 5.2.3 on 2025-06-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cripto1', '0002_alter_blockchainstate_max_supply_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('USER_MANAGEMENT', 'Gestione Utenti'), ('TRANSACTION_MANAGEMENT', 'Gestione Transazioni'), ('BLOCKCHAIN_MANAGEMENT', 'Gestione Blockchain'), ('SYSTEM_ADMIN', 'Amministrazione Sistema'), ('AUDIT_LOGS', 'Log di Audit'), ('SECURITY', 'Sicurezza'), ('REPORTS', 'Report e Analytics')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permesso',
                'verbose_name_plural': 'Permessi',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ruolo Utente',
                'verbose_name_plural': 'Ruoli Utente',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='Cripto1_aud_action__584e8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='Cripto1_aud_severit_682fec_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sso_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sso_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registrazione'), ('CREATE_TRANSACTION', 'Creazione Transazione'), ('VIEW_TRANSACTION', 'Visualizzazione Transazione'), ('DOWNLOAD_FILE', 'Download File'), ('DECRYPT_MESSAGE', 'Decifratura Messaggio'), ('MINE_BLOCK', 'Mining Blocco'), ('EDIT_PROFILE', 'Modifica Profilo'), ('RESET_PRIVATE_KEY', 'Reset Chiave Privata'), ('ADMIN_ACTION', 'Azione Amministrativa'), ('SECURITY_EVENT', 'Evento di Sicurezza'), ('EXPORT_DATA', 'Export Dati'), ('VERIFY_BLOCKCHAIN', 'Verifica Blockchain'), ('USER_MANAGEMENT', 'Gestione Utenti'), ('SYSTEM_EVENT', 'Evento di Sistema'), ('ROLE_ASSIGNMENT', 'Assegnazione Ruolo'), ('PERMISSION_CHANGE', 'Modifica Permessi'), ('USER_ACTIVATION', 'Attivazione Utente'), ('USER_DEACTIVATION', 'Disattivazione Utente'), ('SSO_LOGIN', 'Login SSO')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'severity', 'timestamp'], name='Cripto1_aud_action__cb5959_idx'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='Cripto1.permission'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='Cripto1.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
