# Generated by Django 5.2.3 on 2025-07-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cripto1', '0003_permission_role_userrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registrazione'), ('CREATE_TRANSACTION', 'Creazione Transazione'), ('VIEW_TRANSACTION', 'Visualizzazione Transazione'), ('DOWNLOAD_FILE', 'Download File'), ('DECRYPT_MESSAGE', 'Decifratura Messaggio'), ('MINE_BLOCK', 'Mining Blocco'), ('EDIT_PROFILE', 'Modifica Profilo'), ('ADMIN_ACTION', 'Azione Amministrativa'), ('SECURITY_EVENT', 'Evento di Sicurezza'), ('EXPORT_DATA', 'Export Dati'), ('VERIFY_BLOCKCHAIN', 'Verifica Blockchain'), ('USER_MANAGEMENT', 'Gestione Utenti'), ('SYSTEM_EVENT', 'Evento di Sistema'), ('ROLE_ASSIGNMENT', 'Assegnazione Ruolo'), ('PERMISSION_CHANGE', 'Modifica Permessi'), ('USER_ACTIVATION', 'Attivazione Utente'), ('USER_DEACTIVATION', 'Disattivazione Utente'), ('SSO_LOGIN', 'Login SSO')], max_length=50),
        ),
    ]
